### ISSUE TITLE
node version 11 install issue

### ISSUE THREAD

**Issue by ToogiiB** [docker-library/official-images#5027] opened 2018-11-02 17:43 UTC
it looks like you updated the node version 11 yesterday. 
the install step started failing with latest docker release. 

The npm install command fails with following error. 
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux_musl-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux_musl-x64-67_binding.node":
```
When I change the node image to v10, it works normally. I don't know what is wrong with your new release and wanted to let you know about the issue observed. Thank you

**Comment by ToogiiB** [comment] 2018-11-02 17:46
npm version: 6.4.1
output of npm -p process.version
```
{ http_parser: '2.8.0',
  node: '11.0.0',
  v8: '7.0.276.28-node.5',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i \n',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```

**Error**
```
> node-sass@4.9.4 install /node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux_musl-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux_musl-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall /node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.4 postinstall /node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.0.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /node_modules/which/which.js:89:16
gyp verb `which` failed     at /node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /node_modules/which/which.js:89:16
gyp verb `which` failed     at /node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /node_modules/isexe/mode.js:8:5
```

**Comment by wglambert** [comment] 2018-11-02 18:32
The URL has a number wrong: `linux_musl-x64-67` there exists [`linux_musl-x64-64`](https://github.com/sass/node-sass/releases/download/v4.9.4/linux_musl-x64-64_binding.node) and [`linux_musl-x64-57`](https://github.com/sass/node-sass/releases/download/v4.9.4/linux_musl-x64-57_binding.node)

Duplicate of https://github.com/sass/node-sass/issues/2535

**Closed by wglambert** 2018-11-02 18:32 UTC

**Comment by wglambert** [comment] 2018-11-02 19:08
If this issue stems from the image itself you'll want to file it with the maintainers https://github.com/nodejs/docker-node/issues

**Comment by nimatullah** [comment] 2018-12-26 06:17
I have got same issue :
