### ISSUE TITLE
centos 8 for ppc64le

### ISSUE THREAD

**Issue by clnperez** [docker-library/official-images#6891] opened 2019-10-31 14:14 UTC
Happy to reopen this in a more appropriate place if needed. Am trying to find out when a ppc64le centos:8 image will be available. One was added for x86 about a month ago:

https://github.com/docker-library/official-images/commit/0127967c7eece3491ee20bebc5fe8c866c23c9e0

/cc @jperrin

**Comment by wglambert** [comment] 2019-10-31 18:07
duplicate of https://github.com/CentOS/sig-cloud-instance-images/issues/86

https://hub.docker.com/_/centos/
- Where to file issue
https://github.com/CentOS/sig-cloud-instance-images/issues

**Closed** 2019-11-01 16:50 UTC
