### ISSUE TITLE
docker:dind (19) is broken in Gitlab-CI

### ISSUE THREAD

**Issue by alwinmarkcf** [docker-library/official-images#6342] opened 2019-07-23 07:39 UTC
Hello,

since the new docker:dind image is out (7hours ago), we have problems with our Gitlab-CI. 
Gitlab runners are not able to bring up the new image version 19.03.0-dind .

```
Running with gitlab-ci-multi-runner 9.5.1 (96b34cc)
  on CF-HZ-RZ17-INT-EX-03 (AEh4A-r5)
Using Docker executor with image docker:git ...
Starting service docker:dind ...
Pulling docker image docker:dind ...
Using docker image docker:dind ID=sha256:6ce0d31cf4d670f84b0f74b1b15910f9e3fde4105232e14b0d360a6a49c05362 for docker service...
Waiting for services to be up and running...

*** WARNING: Service runner-AEh4A-r5-project-92-concurrent-0-docker-0 probably didn't start properly.

service runner-AEh4A-r5-project-92-concurrent-0-docker-0-wait-for-service did timeout

2019-07-23T07:24:07.633951217Z Generating RSA private key, 4196 bit long modulus (2 primes)
2019-07-23T07:24:11.040073302Z ........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................++++
2019-07-23T07:24:11.644536925Z ..........................................................................................................++++
2019-07-23T07:24:11.644938386Z e is 65537 (0x010001)
2019-07-23T07:24:11.662442996Z Generating RSA private key, 4196 bit long modulus (2 primes)
2019-07-23T07:24:12.996446402Z ............................................................................................................................................................................................................................................++++
2019-07-23T07:24:13.533920169Z ..............................................................................................++++
2019-07-23T07:24:13.534312040Z e is 65537 (0x010001)
2019-07-23T07:24:13.561694823Z Signature ok
2019-07-23T07:24:13.561714038Z subject=CN = docker:dind server
2019-07-23T07:24:13.561719928Z Getting CA Private Key
2019-07-23T07:24:13.576661985Z /certs/server/cert.pem: OK
2019-07-23T07:24:13.579949780Z Generating RSA private key, 4196 bit long modulus (2 primes)
2019-07-23T07:24:13.637737857Z ........++++
2019-07-23T07:24:13.963874304Z ........................................................++++
2019-07-23T07:24:13.964181867Z e is 65537 (0x010001)
2019-07-23T07:24:13.987654505Z Signature ok
2019-07-23T07:24:13.987664674Z subject=CN = docker:dind client
2019-07-23T07:24:13.987668067Z Getting CA Private Key
2019-07-23T07:24:14.002910162Z /certs/client/cert.pem: OK
2019-07-23T07:24:14.182193314Z time="2019-07-23T07:24:14.181768700Z" level=info msg="Starting up"
2019-07-23T07:24:14.186663483Z time="2019-07-23T07:24:14.186385638Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
2019-07-23T07:24:14.191746714Z time="2019-07-23T07:24:14.191457283Z" level=info msg="libcontainerd: started new containerd process" pid=53
2019-07-23T07:24:14.191784762Z time="2019-07-23T07:24:14.191594480Z" level=info msg="parsed scheme: \"unix\"" module=grpc
2019-07-23T07:24:14.191798918Z time="2019-07-23T07:24:14.191630994Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
2019-07-23T07:24:14.191810686Z time="2019-07-23T07:24:14.191678131Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
2019-07-23T07:24:14.191836681Z time="2019-07-23T07:24:14.191716933Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
2019-07-23T07:24:14.201601663Z time="2019-07-23T07:24:14.192686054Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00087a850, CONNECTING" module=grpc
2019-07-23T07:24:14.304609596Z time="2019-07-23T07:24:14.304218526Z" level=info msg="starting containerd" revision=894b81a4b802e4eb2a91d1ce216b8817763c29fb version=v1.2.6 
2019-07-23T07:24:14.305248715Z time="2019-07-23T07:24:14.305007851Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." type=io.containerd.content.v1 
2019-07-23T07:24:14.305282814Z time="2019-07-23T07:24:14.305198943Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." type=io.containerd.snapshotter.v1 
2019-07-23T07:24:14.305849776Z time="2019-07-23T07:24:14.305608129Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
2019-07-23T07:24:14.305879228Z time="2019-07-23T07:24:14.305643221Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.aufs"..." type=io.containerd.snapshotter.v1 
2019-07-23T07:24:14.318012248Z time="2019-07-23T07:24:14.317656090Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "ip: can't find device 'aufs'\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" 
2019-07-23T07:24:14.318044661Z time="2019-07-23T07:24:14.317691176Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1 
2019-07-23T07:24:14.318056815Z time="2019-07-23T07:24:14.317857647Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1 
2019-07-23T07:24:14.318496347Z time="2019-07-23T07:24:14.318219374Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1 
2019-07-23T07:24:14.318947508Z time="2019-07-23T07:24:14.318590407Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
2019-07-23T07:24:14.318976066Z time="2019-07-23T07:24:14.318623627Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1 
2019-07-23T07:24:14.318988747Z time="2019-07-23T07:24:14.318707012Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "ip: can't find device 'aufs'\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" 
2019-07-23T07:24:14.319000091Z time="2019-07-23T07:24:14.318733093Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
2019-07-23T07:24:14.319010462Z time="2019-07-23T07:24:14.318749384Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
2019-07-23T07:24:14.328089985Z time="2019-07-23T07:24:14.327741445Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1 
2019-07-23T07:24:14.328141744Z time="2019-07-23T07:24:14.327784750Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1 
2019-07-23T07:24:14.328161112Z time="2019-07-23T07:24:14.327867243Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1 
2019-07-23T07:24:14.328173470Z time="2019-07-23T07:24:14.327900083Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1 
2019-07-23T07:24:14.328183675Z time="2019-07-23T07:24:14.327923658Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1 
2019-07-23T07:24:14.328193456Z time="2019-07-23T07:24:14.327968149Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1 
2019-07-23T07:24:14.328203036Z time="2019-07-23T07:24:14.328012328Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1 
2019-07-23T07:24:14.328214331Z time="2019-07-23T07:24:14.328058457Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1 
2019-07-23T07:24:14.328223983Z time="2019-07-23T07:24:14.328087925Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1 
2019-07-23T07:24:14.328233657Z time="2019-07-23T07:24:14.328127004Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1 
2019-07-23T07:24:14.328849941Z time="2019-07-23T07:24:14.328612260Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2 
2019-07-23T07:24:14.329692204Z time="2019-07-23T07:24:14.329368570Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1 
2019-07-23T07:24:14.330690609Z time="2019-07-23T07:24:14.330336706Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1 
2019-07-23T07:24:14.330722765Z time="2019-07-23T07:24:14.330393111Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1 
2019-07-23T07:24:14.330735033Z time="2019-07-23T07:24:14.330501827Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.330745019Z time="2019-07-23T07:24:14.330532951Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.330754554Z time="2019-07-23T07:24:14.330554833Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.330764258Z time="2019-07-23T07:24:14.330581443Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.330773713Z time="2019-07-23T07:24:14.330601250Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.330792643Z time="2019-07-23T07:24:14.330619880Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.330806033Z time="2019-07-23T07:24:14.330639689Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.330815692Z time="2019-07-23T07:24:14.330659679Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.330825075Z time="2019-07-23T07:24:14.330679613Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1 
2019-07-23T07:24:14.332436436Z time="2019-07-23T07:24:14.332093308Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.332472653Z time="2019-07-23T07:24:14.332154697Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.332484934Z time="2019-07-23T07:24:14.332177620Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.332494817Z time="2019-07-23T07:24:14.332198663Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1 
2019-07-23T07:24:14.332970480Z time="2019-07-23T07:24:14.332708856Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock" 
2019-07-23T07:24:14.333002174Z time="2019-07-23T07:24:14.332836918Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock" 
2019-07-23T07:24:14.333014476Z time="2019-07-23T07:24:14.332865538Z" level=info msg="containerd successfully booted in 0.029922s" 
2019-07-23T07:24:14.340464793Z time="2019-07-23T07:24:14.340147820Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00087a850, READY" module=grpc
2019-07-23T07:24:14.345004642Z time="2019-07-23T07:24:14.344674786Z" level=info msg="Setting the storage driver from the $DOCKER_DRIVER environment variable (overlay2)"
2019-07-23T07:24:14.345520540Z time="2019-07-23T07:24:14.345089513Z" level=info msg="parsed scheme: \"unix\"" module=grpc
2019-07-23T07:24:14.345555620Z time="2019-07-23T07:24:14.345154002Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
2019-07-23T07:24:14.345568476Z time="2019-07-23T07:24:14.345202209Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
2019-07-23T07:24:14.345579575Z time="2019-07-23T07:24:14.345247889Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
2019-07-23T07:24:14.345591518Z time="2019-07-23T07:24:14.345380871Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000901f90, CONNECTING" module=grpc
2019-07-23T07:24:14.347213502Z time="2019-07-23T07:24:14.346861368Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000901f90, READY" module=grpc
2019-07-23T07:24:14.350188144Z time="2019-07-23T07:24:14.349885519Z" level=info msg="parsed scheme: \"unix\"" module=grpc
2019-07-23T07:24:14.350245911Z time="2019-07-23T07:24:14.350016890Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
2019-07-23T07:24:14.350264897Z time="2019-07-23T07:24:14.350162199Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
2019-07-23T07:24:14.350489855Z time="2019-07-23T07:24:14.350265855Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
2019-07-23T07:24:14.350775913Z time="2019-07-23T07:24:14.350465120Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000892560, CONNECTING" module=grpc
2019-07-23T07:24:14.351247768Z time="2019-07-23T07:24:14.350960540Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000892560, READY" module=grpc
2019-07-23T07:24:14.446876522Z time="2019-07-23T07:24:14.446571403Z" level=info msg="Loading containers: start."
2019-07-23T07:24:14.468883306Z time="2019-07-23T07:24:14.468476723Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'\nbridge                146976  1 br_netfilter\nstp                    12976  1 bridge\nllc                    14552  2 bridge,stp\nip: can't find device 'br_netfilter'\nbr_netfilter           22256  0 \nbridge                146976  1 br_netfilter\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
2019-07-23T07:24:14.481114043Z time="2019-07-23T07:24:14.480734560Z" level=warning msg="Running modprobe nf_nat failed with message: `ip: can't find device 'nf_nat'\nnf_nat_masquerade_ipv4    13412  1 ipt_MASQUERADE\nnf_nat_ipv4            14115  1 iptable_nat\nnf_nat                 26787  2 nf_nat_masquerade_ipv4,nf_nat_ipv4\nnf_conntrack          133053  5 nf_nat_masquerade_ipv4,nf_nat_ipv4,nf_nat,nf_conntrack_ipv4,xt_conntrack\nlibcrc32c              12644  4 xfs,nf_nat,dm_persistent_data,nf_conntrack\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
2019-07-23T07:24:14.493202266Z time="2019-07-23T07:24:14.492875999Z" level=warning msg="Running modprobe xt_conntrack failed with message: `ip: can't find device 'xt_conntrack'\nxt_conntrack           12760  4 \nnf_conntrack          133053  5 nf_nat_masquerade_ipv4,nf_nat_ipv4,nf_nat,nf_conntrack_ipv4,xt_conntrack\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
2019-07-23T07:24:14.639483316Z time="2019-07-23T07:24:14.639114123Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
2019-07-23T07:24:14.713138514Z time="2019-07-23T07:24:14.712820918Z" level=info msg="Loading containers: done."
2019-07-23T07:24:14.771035152Z time="2019-07-23T07:24:14.770651016Z" level=info msg="Docker daemon" commit=aeac9490dc graphdriver(s)=overlay2 version=19.03.0
2019-07-23T07:24:14.771079517Z time="2019-07-23T07:24:14.770933953Z" level=info msg="Daemon has completed initialization"
2019-07-23T07:24:14.814745736Z time="2019-07-23T07:24:14.814344356Z" level=info msg="API listen on [::]:2376"
2019-07-23T07:24:14.814795769Z time="2019-07-23T07:24:14.814372507Z" level=info msg="API listen on /var/run/docker.sock"
```

Version: docker:18-dind  is working as expected.

**Comment by mbjolin** [comment] 2019-07-23 15:40
https://forum.gitlab.com/t/dind-gitlab-runner-service-doesnt-start-up-suddenly/28311

**Comment by yosifkit** [comment] 2019-07-23 19:46
Duplicate of https://github.com/docker-library/docker/issues/170

**Closed by yosifkit** 2019-07-23 19:46 UTC
