### ISSUE TITLE
Latest ubuntu 16.04 does not have the 'locales' package installed in the base image

### ISSUE THREAD

**Issue by orf** [docker-library/official-images#2856] opened 2017-04-13 09:21 UTC
(I could not find a specific Ubuntu issue page to submit this).

In the latest update of the Ubuntu 16.04 official image (perhaps due to e6eff5692ae9b4c8fdd101fd16f4df30b0b7d36c) the `locales` package is missing, but it is installed by default on every other image. Pulling `16.04` now breaks any image that depends on `locale-gen` being available without installing.

Locale-gen is available by default in: 12.04, 14.04, 14.10 and 16.10.

**Comment by mitar** [comment] 2017-04-14 04:33
I see that really locales has been removed with this pull request: #2852

**Comment by mitar** [comment] 2017-04-14 04:42
Based on reading [this issue](https://github.com/tianon/docker-brew-ubuntu-core/issues/81), it seems this is an upstream bug. I have found [this one already reported](https://bugs.launchpad.net/cloud-images/+bug/1682305).

**Comment by OddBloke** [comment] 2017-04-17 22:01
Hi @orf, @mitar,

For a majority of use cases, locale and timezone data takes up extra space without being used. We _have_ intentionally removed these from minimal images, as part of our drive to keep Ubuntu as the best choice for Docker users. This change reduces the size of the Docker image by ~8%. This represents a substantial space saving, and a corresponding increase in container density.

If you need locales and/or tzdata for your application, you'll want to modify your scripting to install them specifically.

Thanks for using Ubuntu!

**Comment by mitar** [comment] 2017-04-17 22:43
But this is a breaking change without really any announcement or public discussion? At least for us consuming these Docker images.

**Comment by RasmusWernerLarsen** [comment] 2017-04-18 09:05
We were hit by this as well, and I'll have to agree with @mitar.

If you expect people to base their work on these images, you cannot just remove major components in the images during releases.

Either launch a "light"/"unstable" version of the image, so people who want to lighten their images immediately can use those or introduce these changes in tandem with new Ubuntu releases, when we'll be looking for breakages anyway.

It cannot really be the intention that users of the images have to explicitly declare every single Ubuntu dependency in the beginning of the image, because you refuse to keep the base package list stable within releases. Please tell me this is just a mistake...

**Comment by tianon** [comment] 2017-04-22 01:06
This is a duplicate of https://github.com/tianon/docker-brew-ubuntu-core/issues/82, which was redirected upstream (https://bugs.launchpad.net/cloud-images/+bug/1682305).  In the future, please file these sorts of issues directly there (being sure to include the `docker` tag, and the information that you're experiencing this with the Docker images).  Thanks!

**Closed by tianon** 2017-04-22 01:06 UTC
