### ISSUE TITLE
Can't pull ubuntu:20.04 and ubuntu:18:04 since last week

### ISSUE THREAD

**Issue by ikimpriv** [docker-library/official-images#14025] opened 2023-02-06 16:38 UTC
Hi! 
Last week our builds started failing with the following errors, trying to pull base ubuntu images from docker hub:

`mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'`

Only the older ubuntu images still working.

I tried docker pull today and it's still failing

`docker pull ubuntu:20.04`
`20.04: Pulling from library/ubuntu`
`mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'`

**Comment by yosifkit** [comment] 2023-02-07 01:01
The Ubuntu images have moved to OCI images: https://github.com/docker-library/official-images/pull/13950 (after a slight snafu https://github.com/docker-library/official-images/issues/13983 & fix https://github.com/docker-library/official-images/pull/13988). Over time, all of the official images will be moving to OCI media types (`application/vnd.oci.*`) instead of the current Docker media types (`application/vnd.docker.*`).

What version of Docker are you using? Docker version `18.06` should be new enough for OCI image support (https://docs.docker.com/engine/release-notes/18.06/#18060-ce).

**Comment by shaik1a** [comment] 2023-02-09 07:19
Hi, Iam also facing same issue

-bash-4.2$ docker --version
Docker version 19.03.1, build 74b1e89
-bash-4.2$

-bash-4.2$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

Docker version is 19.03.1 and not able to pull ubuntu.

**Comment by tianon** [comment] 2023-02-09 21:00
Can you please post the full output of `docker version` and `docker info`?  Telling us which version of the Docker CLI you're running doesn't really help. :smile:

**Comment by ikimpriv** [comment] 2023-02-09 21:15
I upgraded docker to the latest version (ubuntu 18.04 / docker 23.0.0) and it works fine now. 
The node was running on a pretty old 2019... docker.
Thank you!

**Comment by shaik1a** [comment] 2023-02-10 04:43
> Can you please post the full output of `docker version` and `docker info`? Telling us which version of the Docker CLI you're running doesn't really help. 😄

Please find the output of docker version and info

-bash-4.2$ docker --version
Docker version 19.03.1, build 74b1e89
-bash-4.2$
-bash-4.2$


-bash-4.2$ docker info
Client:
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.6.0)

Server:
 Containers: 24
  Running: 8
  Paused: 0
  Stopped: 16
 Images: 195
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: -
 runc version: -
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.27.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.51GiB
 Name: devcent74-55
 ID: -
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  artifactory.com
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by slieschke** [comment] 2023-02-10 17:13
It looks like Docker 19.03 had a regression where OCI image support was broken per https://github.com/moby/moby/issues/39727

**Comment by tianon** [comment] 2023-02-10 18:46
Ah, nice catch!  So if you update to 19.03.5 or newer, it should be fixed (although it would honestly be in your best interest to update to 20.10.x or even the newly released 23, as the 19.03.x branch is long-since EOL).

**Closed** 2023-12-19 00:03 UTC
