### ISSUE TITLE
ubuntu trusty images cannot update apt repo on non-x86_64 arch

### ISSUE THREAD

**Issue by andrewhsu** [docker-library/official-images#3560] opened 2017-10-10 00:17 UTC
With a `ubuntu:trusty` image, cannot update apt repo index:
```
$ docker run --rm ubuntu:trusty apt-get update # on armv7l
...
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/multiverse/binary-armhf/Packages  404  Not Found [IP: 91.189.88.152 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Looks like there does not exist a `binary-armhf` dir in `multiverse`:
http://security.ubuntu.com/ubuntu/dists/trusty-security/multiverse/

Whereas an older repo endpoint for `trusty-security` seems to have `binary-armhf`: http://ports.ubuntu.com/ubuntu-ports/dists/trusty-security/multiverse/

**Comment by tianon** [comment] 2017-10-10 00:18
Duplicate of https://github.com/tianon/docker-brew-ubuntu-core/issues/96.

See https://bugs.launchpad.net/bugs/1711735 for the upstream ticket tracking this issue.

**Closed by tianon** 2017-10-10 00:18 UTC

**Comment by andrewhsu** [comment] 2017-10-10 00:40
I'm able to workaround by changing the repo definition inside of the `ubuntu:trusty` container:
```
$ sed -i 's|security.ubuntu.com/ubuntu|ports.ubuntu.com/ubuntu-ports|' /etc/apt/sources.list
```

And then update of repo works:
```
$ apt-get update
...
Get:1 http://ports.ubuntu.com trusty-security/universe Sources [76.3 kB]       
Get:2 http://ports.ubuntu.com trusty-security/main armhf Packages [688 kB]     
Get:3 http://ports.ubuntu.com trusty-security/restricted armhf Packages [10.3 kB]
Get:4 http://ports.ubuntu.com trusty-security/universe armhf Packages [239 kB] 
Hit http://ports.ubuntu.com trusty-security/multiverse armhf Packages          
Hit http://ports.ubuntu.com trusty/universe Sources                            
Hit http://ports.ubuntu.com trusty/main armhf Packages                         
Hit http://ports.ubuntu.com trusty/restricted armhf Packages                   
Hit http://ports.ubuntu.com trusty/universe armhf Packages                     
Hit http://ports.ubuntu.com trusty/multiverse armhf Packages                   
Fetched 1013 kB in 17s (56.5 kB/s)                                             
Reading package lists... Done
```

It looks to me the `ports.ubuntu.com` endpoint is updated same time as the `security.ubuntu.com`, but I haven't done an exhaustive list of what security packages are suppose to be in there.

**Comment by andrewhsu** [comment] 2017-10-10 00:43
Related from long ago: https://github.com/moby/moby/issues/32335 unable to build docker armhf ubuntu xenial

**Comment by tianon** [comment] 2017-10-11 20:09
Yeah, it seems to be a resurfaced issue; good find. :disappointed:

Hopefully they fix their builds soon. :disappointed:
