### ISSUE TITLE
Ruby 2.6.1

### ISSUE THREAD

**Issue by n-rodriguez** [docker-library/official-images#5381] opened 2019-02-01 02:41 UTC
Hi there!

It would be nice to have an upgraded version of Docker Ruby.

Thank you!

**Comment by tianon** [comment] 2019-02-01 03:11
Duplicate of https://github.com/docker-library/ruby/issues/263

I'm on my phone ATM, but if you wanted to help out, you could clone that repository, run `./generate-stackbrew-library.sh`, and open a PR here replacing the contents of `library/ruby` with the output. 👍

**Closed by tianon** 2019-02-01 03:11 UTC
