### ISSUE TITLE
Latest ubuntu 16.04 does not have the 'tzdata' package installed in the base image

### ISSUE THREAD

**Issue by mitar** [docker-library/official-images#2863] opened 2017-04-14 04:28 UTC
I think this is similar to #2856. But since a day ago [my xenial image is not building anymore](https://hub.docker.com/r/tozd/base/builds/). The reason is that `tzdata` is not available anymore for some reason.

**Comment by mitar** [comment] 2017-04-14 04:33
I see that really tzdata has been removed with this pull request: #2852

**Comment by mitar** [comment] 2017-04-14 04:37
Based on reading [this issue](https://github.com/tianon/docker-brew-ubuntu-core/issues/81), it seems this is an upstream bug. I have found [this one already reported](https://bugs.launchpad.net/cloud-images/+bug/1682622).

**Comment by OddBloke** [comment] 2017-04-17 22:01
Hi @mitar,

For a majority of use cases, locale and timezone data takes up extra space without being used. We _have_ intentionally removed these from minimal images, as part of our drive to keep Ubuntu as the best choice for Docker users. This change reduces the size of the Docker image by ~8%. This represents a substantial space saving, and a corresponding increase in container density.

If you need locales and/or tzdata for your application, you'll want to modify your scripting to install them specifically.

Thanks for using Ubuntu!

**Comment by mtparet** [comment] 2017-04-18 12:17
Hi @OddBloke,

Did you inform of this breaking change through a mailing list or something else ? So we could handle it before it breaks our images.

Does it means we should not based our images on an Ubuntu version (16.04/17.04 etc..) but on a specific Ubuntu Docker build tag (xenial-20170410/xenial-20170119 etc..) and so we need to manually change the tag for each new Ubuntu Docker build  ?

Best,

Matthieu

**Comment by rymohr** [comment] 2017-04-21 23:13
We just got burned by this one too.

This change will cause a runtime error for anyone using `ubuntu:16.04` as a base image for a rails app. And they won't notice it until they try to rebuild their image from scratch.

**Comment by tianon** [comment] 2017-04-22 01:07
This is a duplicate of https://github.com/tianon/docker-brew-ubuntu-core/issues/82, which was redirected upstream (https://bugs.launchpad.net/cloud-images/+bug/1682305).  In the future, please file these sorts of issues directly there (being sure to include the `docker` tag, and the information that you're experiencing this with the Docker images).  Thanks!

**Closed by tianon** 2017-04-22 01:07 UTC

**Comment by satishpatro44** [comment] 2019-06-19 05:54
I am facing the same issue even in Ubuntu 18.04. Even, I manually tried to install using gem
`gem install tzinfo-data`
It got installed, but the issue still persist
