### ISSUE TITLE
addgroup fails

### ISSUE THREAD

**Issue by elderone** [docker-library/official-images#135] opened 2014-08-01 10:24 UTC
docker run -i -t stackbrew/ubuntu:12.04 /bin/bash
apt-get install -y ssh-client
...
Setting up openssh-client (1:5.9p1-5ubuntu1.4) ...
groupadd: failure while writing changes to /etc/group
addgroup: `/usr/sbin/groupadd -g 102 ssh' returned error code 10. Exiting.
dpkg: error processing openssh-client (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up xauth (1:1.0.6-1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Errors were encountered while processing:
 openssh-client
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by yosifkit** [comment] 2015-01-22 23:39
I am unable to reproduce this and it seems to be related to SELinux. Closing for now.

**Closed by yosifkit** 2015-01-22 23:39 UTC
