### ISSUE TITLE
Outdated DockerHub URLs in Readme

### ISSUE THREAD

**Issue by filipre** [docker-library/official-images#6234] opened 2019-07-05 16:23 UTC
Hi! 
Following links are outdated in the README since most (any?) of them lead to a 404

<img width="900" alt="Screenshot 2019-07-05 at 18 21 16" src="https://user-images.githubusercontent.com/8502198/60734915-d79bf380-9f51-11e9-85ae-fad24872fbfb.png">

Greetings
René

**Comment by tianon** [comment] 2019-07-05 16:24
I can't reproduce:

![image](https://user-images.githubusercontent.com/161631/60735007-9fbb8e80-9f06-11e9-97e0-a5e1bcc58f41.png)

**Comment by filipre** [comment] 2019-07-05 16:31
🤔There is something weird going on. I would now assume that "/u/amd64" should be working and that Docker did not initiate a name change. Right?

<img width="1426" alt="Screenshot 2019-07-05 at 18 26 53" src="https://user-images.githubusercontent.com/8502198/60735154-8a6c5180-9f52-11e9-84c7-82818ba722f1.png">

<img width="1426" alt="Screenshot 2019-07-05 at 18 28 10" src="https://user-images.githubusercontent.com/8502198/60735196-ad970100-9f52-11e9-97d7-ea8734862925.png">

**Comment by wglambert** [comment] 2019-07-08 19:50
Looks like an issue with Dockerhub, unauthenticated users get 401 unauthorized in the F12 console

And when logged into a normal user account:
>Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

Viewing a repository works normal https://hub.docker.com/r/amd64/node
Viewing the user account fails https://hub.docker.com/u/amd64

**Comment by wglambert** [comment] 2019-07-08 19:53
Closing as https://github.com/docker/hub-feedback/issues/1841 exists

**Closed by wglambert** 2019-07-08 19:53 UTC
