### ISSUE TITLE
amd64 architecture for wordpress:5.9

### ISSUE THREAD

**Issue by mvhirsch** [docker-library/official-images#11756] opened 2022-01-27 10:43 UTC
Hi,

I really appreciate your work, thanks for all! :heart: 

Just wanted to pull latest `wordpress:5.9` but it misses amd64 architecture. 
Stuck in queue? (I'm unable to find the build queues.) Maybe I'm just impatient. If so, please let me know.

```
pulling wordpress (wordpress:5.9)...
5.9: Pulling from library/wordpress
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

![Screenshot from 2022-01-27 11-42-02](https://user-images.githubusercontent.com/573047/151343401-19648b57-9e58-47a1-80d9-469adada9db9.png)

**Comment by yosifkit** [comment] 2022-01-27 17:29
Duplicate of https://github.com/docker-library/wordpress/issues/687; see https://github.com/docker-library/wordpress/issues/687#issuecomment-1023468645

**Closed by yosifkit** 2022-01-27 17:29 UTC
