### ISSUE TITLE
Golang:latest points to 1.10(.0) and golang:1.11 points to 1.11.1 despite 1.11.4 being out

### ISSUE THREAD

**Issue by HaraldNordgren** [docker-library/official-images#5229] opened 2018-12-26 02:27 UTC
```
 % docker run golang go version
go version go1.10 linux/amd64

 % docker run golang:latest go version
go version go1.10 linux/amd64

 % docker run golang:1.11 go version
go version go1.11.1 linux/amd64
```

**Comment by wglambert** [comment] 2018-12-26 18:07
Duplicate of https://github.com/docker-library/golang/issues/258

---
`docker run` doesn't auto update the image

```console
$ docker pull golang:latest
latest: Pulling from library/golang
Digest: sha256:759554aca1303b463d428a8f81b0fed648563ed3defc2d8e5577b763691def20
Status: Image is up to date for golang:latest

$ docker run golang go version
go version go1.11.4 linux/amd64
```

**Closed by wglambert** 2018-12-26 18:07 UTC
