### ISSUE TITLE
Could we add i386/centos:6?

### ISSUE THREAD

**Issue by ericcurtin** [docker-library/official-images#3733] opened 2017-11-21 12:12 UTC
At least I would find it handy, I'm sure many others would too. As this is one of the most popular i386 platforms. Probably more popular than many of the ones already supported. There is already an unofficial image here:

https://hub.docker.com/r/toopher/centos-i386/

Kudos to toopher. But I'd like to see an official version for centos:6, one I know I can trust. Willing to open the PR! If you guys know another PR I can use as a reference, maybe from adding another i386 platform. That would be great!

**Comment by tianon** [comment] 2017-11-21 17:39
This is a duplicate of https://github.com/CentOS/sig-cloud-instance-images/issues/51 (which is the correct place to discuss this to ensure it's in a place the image maintainers will see -- this repo is too high-frequency for the maintainers of most of the individual images to follow it very actively).

**Closed by tianon** 2017-11-21 17:39 UTC
