### ISSUE TITLE
Fedora latest tag pointing to older image

### ISSUE THREAD

**Issue by siddharthvipul** [docker-library/official-images#8315] opened 2020-07-07 08:13 UTC
I have a merged [PR](https://github.com/docker-library/official-images/pull/8240) to point the latest tag to a newer image (version 32). On the docker hub website Fedora readme, it's correctly showing version [32 is the latest](https://hub.docker.com/_/fedora). But when pulling using `docker pull fedora:latest` it pulls 31.
I tried pulling version 32 by itself and it works as expected (pulled f32).

I see different digests for 32 and latest tags on dockerhub [f32](https://hub.docker.com/layers/fedora/library/fedora/32/images/sha256-df6e2e0f4435151ea77a444965b485ae23380a3d239dfa9f5e83d422d2d524b5?context=explore) vs [latest](https://hub.docker.com/layers/fedora/library/fedora/latest/images/sha256-829948d9a54ca9926c7fa01a976bbeccf38d66e85b558ca61f4b589246ab2d26?context=explore)

Do I have to update something else other than already [udpated tag](https://github.com/docker-library/official-images/blob/5f24b543efd30b0daa35c32f02f3d927bfaf9c7d/library/fedora#L60)?

**Comment by siddharthvipul** [comment] 2020-07-07 08:17
also (not sure if's relevant), https://download.docker.com/linux/fedora/ has no f32 directory,
Is there something I can do to update it there? :)
apologies if these are too obvious... I have recently started doing this

**Comment by wglambert** [comment] 2020-07-07 16:32
There's an open PR for this issue https://github.com/docker-library/official-images/pull/8164

You can pull `fedora:32` in the meantime

**Comment by raveit65** [comment] 2020-07-07 16:55
> You can pull `fedora:32` in the meantime

Thanks but not practicable.
We (Mate desktop) are using fedora docker images for a lot of repos with different branches at github with Travis CI.
https://github.com/mate-desktop
The idea of the latest tag is not to change our configs every 6 months.
Ok, we have to wait...

**Comment by tianon** [comment] 2020-07-07 17:02
Arg, https://github.com/docker-library/official-images/pull/8240 has suffered from https://github.com/docker-library/bashbrew/issues/8.

We wouldn't have run into this issue if https://github.com/docker-library/official-images/pull/8164 had been merged instead (since it would've then rebuilt `fedora:32`).  I'll see if I can update it by hand instead.

> also (not sure if's relevant), https://download.docker.com/linux/fedora/ has no f32 directory,

That's not something we're involved with -- looking at https://github.com/docker/docker-ce-packaging, it appears to have been added in https://github.com/docker/docker-ce-packaging/commit/b6331a2a58223ee528f0943ae95e8eb993a69b76, so it's probably just waiting for the next (major) release of Docker (cc @thaJeztah).

**Comment by tianon** [comment] 2020-07-07 17:22
This is now fixed: https://github.com/docker-library/repo-info/commit/664c661b3381e2ca004cec71c3c59c813619c56c

**Closed by tianon** 2020-07-07 17:22 UTC

**Comment by raveit65** [comment] 2020-07-08 08:56
I can confirm that the issue is fixed and fedora 32 is used with our Travis CI builds.
From today:
https://travis-ci.org/github/mate-desktop/mate-terminal/jobs/706084787#L213

Thanks a lot for fixing this.
