### ISSUE TITLE
Upgrade rethinkdb to 2.1.2.

### ISSUE THREAD

**Issue by Ti-webdev** [docker-library/official-images#1030] opened 2015-09-06 08:30 UTC

**Comment by md5** [comment] 2015-09-06 15:35
This is a duplicate of https://github.com/stuartpb/rethinkdb-dockerfiles/issues/12

**Comment by dalanmiller** [comment] 2015-10-06 15:19
Also duplicate now of #1099

**Closed** 2015-10-06 16:15 UTC
